
name: Publish to Google Artifcact Registry

on:
  push:
    branches: [ main, google-artifact-registry ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GAR_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.GAR_REGISTRY }}/${{ secrets.GAR_REPOSITORY }}/bakerscraper:latest
